[unix_http_server]
file=/run/supervisor.sock
chmod=0700

[supervisord]
nodaemon=true
logfile=/dev/null
pidfile=/run/supervisord.pid
user=root

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///run/supervisor.sock

[program:postgres]
command=/opt/shore-sentinel/bin/run-process.sh postgres
priority=10
autostart=true
autorestart=unexpected
startsecs=3
stopasgroup=true
killasgroup=true
stopwaitsecs=30
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:redis]
command=/opt/shore-sentinel/bin/run-process.sh redis
priority=10
autostart=true
autorestart=unexpected
startsecs=2
stopasgroup=true
killasgroup=true
stopwaitsecs=15
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:minio]
command=/opt/shore-sentinel/bin/run-process.sh minio
priority=10
autostart=true
autorestart=unexpected
startsecs=3
stopasgroup=true
killasgroup=true
stopwaitsecs=20
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:api]
command=/opt/shore-sentinel/bin/run-process.sh api
priority=20
autostart=true
autorestart=unexpected
startsecs=5
stopasgroup=true
killasgroup=true
stopwaitsecs=30
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:worker-node]
command=/opt/shore-sentinel/bin/run-process.sh worker-node
priority=20
autostart=true
autorestart=unexpected
startsecs=5
stopasgroup=true
killasgroup=true
stopwaitsecs=30
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:worker-python]
command=/opt/shore-sentinel/bin/run-process.sh worker-python
priority=20
autostart=true
autorestart=unexpected
startsecs=3
stopasgroup=true
killasgroup=true
stopwaitsecs=15
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:web]
command=/opt/shore-sentinel/bin/run-process.sh web
priority=30
autostart=true
autorestart=unexpected
startsecs=5
stopasgroup=true
killasgroup=true
stopwaitsecs=30
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
[group:shore-sentinel]
programs=postgres,redis,minio,api,worker-node,worker-python,web
priority=999
