import {Header} from '@/components/ui';
const severityTone={critical:'red',high:'red',medium:'amber',low:'yellow',informational:'blue'};
const severityExplanations={critical:'Active exploitation or confirmed compromise. Stop other work and triage now.',high:'High-confidence finding with meaningful blast radius. Address in this operational window.',medium:'Material weakness that raises risk. Plan remediation in the next hardening pass.',low:'Minor weakness or hygiene item. Track and fix when schedule allows.',informational:'Context, best-practice note, or inert observation. No immediate action required.'};
const severityOrder=['critical','high','medium','low','informational'];
const severityLabels={critical:'Critical',high:'High',medium:'Medium',low:'Low',informational:'Informational'};
const prioritizationOrder=[{key:'critical',blurb:'Triage before all other work — active exploitation or confirmed compromise.'},{key:'high',blurb:'Address in the current operational window — meaningful blast radius and high scanner confidence.'},{key:'medium',blurb:'Schedule in the next hardening pass — material weakness that compounds risk if left open.'},{key:'low',blurb:'Fix when schedule allows — minor weakness or hygiene item that does not meaningfully expand exposure.'},{key:'informational',blurb:'Review on cadence — context or best-practice note with no immediate action required.'}];
export default function KB(){return <div className='stack'>
<Header eye='Secondary reference' title='Knowledgebase' desc='Reference material is available without becoming a primary navigation item.'/>
<section className='panel' id='managed-check-in'><h2>How managed machines check in</h2><p>Managed machines use approved pull-agent or SSH-push flows and feed fleet health views.</p></section>
<section className='panel' id='audit-history'><h2>How one-time audits stay separate</h2><p>Ad hoc audits are searchable evidence records and stay out of managed fleet health unless promoted.</p></section>
<section className='panel' id='severity-scoring'><h2 id='severity-scoring'>How severity is calculated</h2><p>Severity reflects scanner-assessed impact and confidence. Each finding is classified into one of five levels. The assigned level determines which &ldquo;Next action&rdquo; the dashboard surfaces and how findings are sorted in remediation queues.</p><dl>{severityOrder.map(s=><div key={s}><dt className='kb-def'>{severityLabels[s]}</dt><dd>{severityExplanations[s]}</dd></div>)}<dt className='kb-def'>Prioritization rule</dt><dd>When multiple findings compete for attention, Shore Sentinel ranks by severity first, then by blast radius and scanner confidence. This keeps the most operationally significant items at the top of every queue without hiding lower-severity context.</dd></dl><p>For managed machines, the fleet-level posture chip shows the highest severity currently active across all enrolled targets.</p></section>
<section className='panel' id='score-explanation'><h2 id='score-explanation'>How security score is derived</h2><p>Each managed machine receives a per-target security score based on two signals:</p><ul><li><strong>Monitoring state</strong> &mdash; enrolled machines with active monitoring contribute a stable baseline because their posture is continuously observed. Machines without monitoring are scored conservatively because posture gaps may exist between spot-checks.</li><li><strong>Scan posture</strong> &mdash; the severity mix of the latest completed scan adjusts the score upward or downward. Open critical findings drag the score lower than open low-severity findings do, because impact and confidence weighting penalize higher-severity exposure more heavily.</li></ul><p>The score is expressed on a 0&ndash;100 scale where <strong>90+ means enrolled and scanning with no critical/high exposure</strong>, <strong>72&ndash;89 means enrolled but with open findings dragging posture down</strong>, and <strong>below 72 means monitoring is off or critical exposure is present</strong>. One-time audits report a provisional score until the first completed scan establishes a baseline.</p></section>
<section className='panel' id='prioritization'><h2 id='prioritization'>How findings are prioritized</h2><p>Findings are sorted and surfaced using a two-level rule that keeps the most important action visible without burying context:</p><ol><li><strong>Severity tier</strong> &mdash; critical findings always appear above high, high above medium, and so on down to informational. This tier order is the primary sort key across the dashboard, remediation queue, and scan reports.</li><li><strong>Operational weight within tier</strong> &mdash; inside the same severity tier, findings with larger blast radius (multi-machine exposure, shared infrastructure) and higher scanner confidence float to the top. Low-confidence or single-offset observations sink to the bottom of their tier so operators act on signal first.</li></ol><p>The &ldquo;Top recommended action&rdquo; card on the remediation page uses this rule to surface the single most operationally significant open finding.</p><ul>{prioritizationOrder.map(p=><li key={p.key}><strong>{severityLabels[p.key]}</strong> &mdash; {p.blurb}</li>)}</ul></section>
</div>;}